### ISSUE TITLE
Bootstrap vs Material UI 

### ISSUE THREAD

**Issue by wilkosz** [saldanan1/DocHubs-App#1]
## Agenda 
Shouldn't mix front end responsive frameworks as
- inevitable to have CSS collisions
- added complexity 
- larger asset required to be served to the client

## Fix
Either pick `material-ui` or `react-bootstrap` for development.

## Background
https://flatlogic.com/blog/bootstrap-vs-material-ui-which-one-to-use-for-the-next-web-app/#:~:text=Bootstrap%20is%20a%20powerful%20CSS,to%20create%20responsive%20web%20applications.&text=Material%20UI%20is%20a%20React,made%20according%20to%20Material%20guidelines.

**Comment by saldanan1** [comment]
Chose material-ui

from commit message:

-Removed react-bootstrap from the project (was legacy code anyway)
-Read up on differences of each, still not sure if one is better than another here, but I prefered Material UI from a first glance

**Comment by wilkosz** [comment]
@saldanan1 This line can be removed from `package.json` in that case `"bootstrap": "^4.5.2"`
