### ISSUE TITLE
Use NPM assets over 3rd party CDN assets where possible

### ISSUE THREAD

**Issue by wilkosz** [saldanan1/DocHubs-App#2]
## Agenda 
When possible always avoid serving assets from 3rd party CDN when there are npm alternatives 

## Fix 
`index.html` contains CDN assets which can be found firstly in your npm packages or through adding another package. These include: 
- `https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css`, this can be loaded by including the import statement `import 'bootstrap/dist/css/bootstrap.min.css';` inside `App.js`, please see the setup instructions https://react-bootstrap.github.io/getting-started/introduction/
-  `https://www.npmjs.com/package/fontsource-roboto`, please see https://www.npmjs.com/package/fontsource-roboto for setup instructions.

**Comment by saldanan1** [comment]
Read up on CDN, I can see the benefit of import vs tags now.

Resolved in most recent commit. Both <link> tags were legacy code, may bring back fontsource-roboto but unsure ATM
