### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by wilkosz** [saldanan1/DocHubs-App#3]
## Agenda 
Many repos will contain build settings specific to the operating system, dependencies, keys, and more. These are all files that will add bloat to the repo in the case of `node_modules`, or security risks when adding environment variable file for resources or 3rd party credentials. 

## Fix 
Use `.gitignore` to remove the association of particular files from your repo. An example of this for react can be found here
https://github.com/facebook/create-react-app/blob/master/.gitignore

**Comment by saldanan1** [comment]
Added a gitignore for node_modules/

Removed Node_modules from the repository with:
```
git rm -r --cached node_modules

git commit -am "node_modules be gone!"

git push origin master
```

Do I need to leave readme instructions on what to packages to install on a fresh pull?
