### ISSUE TITLE
Remove Section Elements

### ISSUE THREAD

**Issue by wilkosz** [saldanan1/DocHubs-App#4]
## Issue 
I really haven't seen the use of HTML section elements in many websites, not sure how conventional it is. 
Google:

> HTML | <section> Tag
> The section tag is used when requirements of two headers or footers or any other section of documents needed. Section tag grouped the generic block of related contents. The main advantage of the section tag is, it is a semantic element, which describes its meaning to both browser and developer.

**Comment by saldanan1** [comment]
Not sure why I even had these in the first place. Probably from a initial web search for a resource that included it. 

Replaced all `sections` with `divs`
