### ISSUE TITLE
Using Grid System

### ISSUE THREAD

**Issue by wilkosz** [saldanan1/DocHubs-App#6]
## Issue 
Your original website (https://noahsaldanadesign.com) did a fantastic job drawing people in to read the content. 
It was responsive and used animation effects. 

New
Not sure about the look and feel/responsiveness
![image](https://user-images.githubusercontent.com/2351142/91655356-514a5580-eaf3-11ea-9740-0e4c90e04318.png)

Old
Great design and responsive
![image](https://user-images.githubusercontent.com/2351142/91655377-73dc6e80-eaf3-11ea-842d-150c9f962d10.png)

I think you need to introduce the Grid system in order to allow the UI to be responsive and mimic the same feel that you previously had https://material-ui.com/components/grid/

**Comment by saldanan1** [comment]
Parts of the project are in a grid (mainly the displaying of the pictures and the text alongside them...

```
<div className={classes.root}>
        <div className={classes.text}>
          <h1 >{props.name}</h1>
            <p>{props.description}</p>
        </div>
        <GridList cellHeight={650}className={classes.gridList} cols={1}>
          {props.link.map((tile) => (
            <GridListTile key={tile} cols={tile.cols || 1}>
                  <img src={tile} alt={tile}/>
            </GridListTile>
          ))}
        </GridList>
      </div>
```
But trying to convert the rest to a similar style is probably preferred. I'll attempt to "grid system" the rest of the project
